<a href="https://colab.research.google.com/github/akifarhan/ML-SchOfAI/blob/master/multinomial_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
# !wget https://raw.githubusercontent.com/huseinzol05/Malaya-Dataset/master/political-landscape/political-landscape.json
!wget https://raw.githubusercontent.com/huseinzol05/Malaya-Dataset/master/emotion/sadness-twitter-malaysia.json

--2019-10-22 22:14:05--  https://raw.githubusercontent.com/huseinzol05/Malaya-Dataset/master/emotion/sadness-twitter-malaysia.json
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8098221 (7.7M) [text/plain]
Saving to: ‘sadness-twitter-malaysia.json’

sadness-twitter-mal 100%[===================>]   7.72M  --.-KB/s    in 0.09s   

2019-10-22 22:14:05 (83.9 MB/s) - ‘sadness-twitter-malaysia.json’ saved [8098221/8098221]



In [0]:
import json

with open('political-landscape.json') as fopen:
  data = json.load(fopen)
data.keys()

dict_keys(['kerajaan', 'pembangkang'])

In [0]:
with open('sadness-twitter-malaysia.json') as fopen:
  apple = json.load(fopen)

In [0]:
kerajaan = data['kerajaan']

In [0]:
pembangkang = data['pembangkang']

In [0]:
import random
k = 500
apple_sample = random.sample(apple, k)
pembangkang_sample = random.sample(pembangkang, k)
kerajaan_sample = random.sample(kerajaan, k)

I want `apple` as class `0`, `pembangkang` class `1`, `kerajaan` class `2`

In [0]:
Y = [0] * k + [1] * k + [2] * k
len(Y)

1500

In [0]:
X = apple_sample + pembangkang_sample + kerajaan_sample
len(X) == len(Y)

True

## Basic text cleaning

In [0]:
for i in range(len(X)):
  X[i] = X[i].lower()

## Bag-of-word

In [0]:
unique_words = list(set(' '.join(X).split()))
len(unique_words)

7732

In [0]:
bow = np.zeros((len(X), len(unique_words)))
bow.shape

(1500, 7732)

In [0]:
for no, x in enumerate(X):
  for w in x.split():
    bow[no, unique_words.index(w)] += 1

In [0]:
string = X[0]
string

'gak terasa air mata menetes,  hati tergetar. semoga allah swt,  memberikan amanah untuk kalian berdua menjadi pemim https://t.co/fdubw5ijak'

In [0]:
for w in string.split():
  print(w, unique_words.index(w))

gak 2537
terasa 6437
air 1445
mata 5912
menetes, 6548
hati 7641
tergetar. 4045
semoga 678
allah 6282
swt, 7396
memberikan 4052
amanah 1006
untuk 6387
kalian 5875
berdua 6626
menjadi 1704
pemim 1955
https://t.co/fdubw5ijak 2309


In [0]:
np.where(bow[0] > 0)

(array([ 678, 1006, 1445, 1704, 1955, 2309, 2537, 4045, 4052, 5875, 5912,
        6282, 6387, 6437, 6548, 6626, 7396, 7641]),)

In [0]:
unique_words[:100]

['think',
 'mon',
 'jahanam',
 'btul..did',
 '@preity_pykah',
 'prabowo',
 'sketch',
 'pencegahan',
 'struktur',
 'mempersoalkan',
 'https://t.co/ozwgpka9lt',
 '@aidelmustaza',
 'fasa',
 'toilet',
 'cepat!',
 'komen',
 'pesaing',
 'mah',
 'ziarah',
 'terlebih',
 'cepat',
 'ph.',
 'sakit...what',
 'perdana',
 'rb.',
 'sem',
 'tonton',
 'ke..',
 'sembang',
 'gelak',
 'sado',
 'petai',
 'ibukotanya',
 'tangani',
 'elakkan',
 'dipenjarakan',
 'rabun',
 'https://t.co/epnb1jvsvw',
 'debate',
 'pembangkang,',
 'jee',
 'knapa',
 'hari2',
 'family',
 'always',
 'yb2',
 'maszlee',
 'mencapai',
 'tu?',
 'bekas',
 'ini',
 'bertindih',
 'https://t.co/pkzv4rq4sn',
 'sehat',
 '119',
 'gobindsinghdeo',
 'menyokong',
 '"saifuddinabd',
 'lee',
 'plihatkan',
 'tubuh,',
 'anakanak',
 'https://t.co/dqdp8rcch5',
 '@umnoonline',
 'keadilan,',
 'beri',
 'bab2',
 'inspirasi',
 'yayasan',
 'zubir',
 'gomen',
 'update',
 'jajan',
 'tweet.',
 '"...turun',
 'senang.',
 'korban',
 'akui',
 'nanti-nantikan.',
 'imut

In [0]:
example_x = ['saya suka makan ayam ayam', 'suka tidur', 'suka menganjing']
example_unique = list(set(' '.join(example_x).split()))
example_unique

['ayam', 'suka', 'saya', 'tidur', 'makan', 'menganjing']

In [0]:
example_bow = np.zeros((len(example_x), len(example_unique)))
example_bow

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [0]:
for no, x in enumerate(example_x):
  for w in x.split():
    example_bow[no, example_unique.index(w)] += 1
    
example_bow

array([[2., 1., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 1.]])

In [0]:
df = np.zeros((len(example_unique)))
df

array([0., 0., 0., 0., 0., 0.])

In [0]:
for no, w in enumerate(example_unique):
  for string in example_x:
    if w in string:
      df[no] += 1
      
df

array([1., 3., 1., 1., 1., 1.])

In [0]:
df = len(example_x) / df # N / df

In [0]:
log_df = np.log(df)
log_df

array([1.09861229, 0.        , 1.09861229, 1.09861229, 1.09861229,
       1.09861229])

In [0]:
example_tfidf = example_bow * log_df
example_tfidf

array([[2.19722458, 0.        , 1.09861229, 0.        , 1.09861229,
        0.        ],
       [0.        , 0.        , 0.        , 1.09861229, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.09861229]])

## Calculate likelihood

In [0]:
classes, counts = np.unique(Y, return_counts = True)
prob_class = {}
for i in range(len(classes)):
  prob_class[classes[i]] = counts[i] / len(Y)
  
prob_class

{0: 0.3333333333333333, 1: 0.3333333333333333, 2: 0.3333333333333333}

In [0]:
np_X = np.array(bow)
np_Y = np.array(Y)

In [0]:
sum_class = {}
for c in classes:
  sum_class[c] = np_X[np_Y == c].sum()
sum_class

{0: 7383.0, 1: 6432.0, 2: 5686.0}

In [0]:
likelihood = np.zeros((len(classes), bow.shape[1]))
likelihood.shape

(3, 7732)

In [0]:
alpha = 1

for c_ in classes:
  c = np_X[np_Y == c_].sum(axis = 0)
  likelihood[c_] = (alpha + c) / (sum_class[c_] + alpha * bow.shape[1])
  
likelihood

array([[1.32318889e-04, 6.61594443e-05, 6.61594443e-05, ...,
        1.32318889e-04, 6.61594443e-05, 6.61594443e-05],
       [7.06015250e-05, 1.41203050e-04, 7.06015250e-05, ...,
        7.06015250e-05, 1.41203050e-04, 7.06015250e-05],
       [7.45267551e-05, 7.45267551e-05, 1.49053510e-04, ...,
        7.45267551e-05, 7.45267551e-05, 1.49053510e-04]])

In [0]:
bow.shape, likelihood.shape

((1500, 7386), (3, 7386))

In [0]:
numerator = np.copy(likelihood)
for c in classes:
  numerator[c] = numerator[c] * prob_class[c] # p(x|c) * p(c)
numerator

array([[2.53659032e-05, 2.53659032e-05, 5.07318063e-05, ...,
        2.53659032e-05, 2.53659032e-05, 2.53659032e-05],
       [2.47224900e-05, 2.47224900e-05, 2.47224900e-05, ...,
        4.94449801e-05, 2.47224900e-05, 2.47224900e-05],
       [4.78102888e-05, 4.78102888e-05, 2.39051444e-05, ...,
        1.19525722e-04, 4.78102888e-05, 4.78102888e-05]])

In [0]:
forward = bow.dot(numerator.T)
x_predict = forward / forward.sum(axis=1, keepdims=True)
x_predict.shape

(1500, 3)

In [0]:
(np.argmax(x_predict, axis = 1) == np_Y).mean()

0.722

In [0]:
x_predict[0]

array([0.74545159, 0.14850722, 0.10604119])

In [0]:
np.argmax(x_predict[0])

0

In [0]:
new_string = ['saya suka government']
new_bow = np.zeros((len(new_string), len(unique_words)))

for no, x in enumerate(new_string):
  for w in x.split():
    if w in unique_words:
      new_bow[no, unique_words.index(w)] += 1
    
new_bow.sum()

3.0

In [0]:
new_bow.shape

(2, 7386)

In [0]:
new_feedforward = new_bow.dot(numerator.T)
new_feedforward / new_feedforward.sum(axis=1, keepdims=True)

array([[0.05117132, 0.49873344, 0.45009524],
       [0.03653975, 0.49858075, 0.4648795 ]])